hw2
svp8/java-course-2024 pull request #2
Opened 2024-02-17 18:55 UTC by svp8

2024-02-29 12:29 UTC, nexen505 requested changes

2024-02-29 12:29 UTC, nexen505 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Bean
Проблема: бины объявлены внутри `@ConfigurationProperties`, что излишне.

Предложение: объявить бины клиентов в отдельной `@Configuration`.

2024-02-29 12:29 UTC, nexen505 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    public GitHubClient gitHubClient(@Value("client.github.baseurl") String baseUrl) {
Проблема: при запуске приложение в клиент передается строка `client.github.baseurl`, а не значение из свойства приложения.

Предложение: исправить синтаксис в `@Value`.

2024-02-29 12:29 UTC, nexen505 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    public StackOverflowClient stackOverflowClient(@Value("client.stack.baseurl") String baseUrl) {
Проблема: при запуске приложение в клиент передается строка `client.stack.baseurl`, а не значение из свойства приложения.

Предложение: исправить синтаксис в `@Value`.

2024-02-29 12:29 UTC, nexen505 commented on scrapper/src/main/java/edu/java/client/GithubClientImpl.java
> +            this.webClient = WebClient.create(BASE_URL);
Проблема: при таком создании клиента вручную теряются предконфигурированные фреймворком компоненты.

Предложение: добавить в конструктор зависимость на `WebClient.Builder webClientBuilder` и использовать ее для создания клиента.

2024-02-29 12:29 UTC, nexen505 commented on scrapper/src/main/java/edu/java/client/StackOverflowClientImpl.java
> +            this.webClient = WebClient.create(BASE_URL);
Проблема: при таком создании клиента вручную теряются предконфигурированные фреймворком компоненты.

Предложение: добавить в конструктор зависимость на `WebClient.Builder webClientBuilder` и использовать ее для создания клиента.

2024-02-29 12:29 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{scheduler.interval}")
Проблема: такое использование SpEL приводит к необходимости делать `Scheduler` бином, что излишне.

Предложение: воспользоваться именно значением свойства приложение через SpEL.

2024-03-02 13:15 UTC, svp8 commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{T(org.springframework.boot.convert.DurationStyle)"
Хорошо ли так писать? Без этого не парсит строки вида 10s,10m. Можно просто ${app.scheduler.interval} оставить, но в properties писать в миллисекундах нужно.

2024-03-05 12:18 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduler/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{T(org.springframework.boot.convert.DurationStyle)"
Правильно подмечаешь, что это усложнение:`10ms` должно работать, если объявить `@ConfigurationProperties` со свойством типа `java.time.Duration`, чего в текущей версии кода не сделано.

2024-03-05 12:22 UTC, nexen505 requested changes

2024-03-05 12:22 UTC, nexen505 commented on scrapper/src/main/java/edu/java/client/GithubClientImpl.java
> +            this.webClient = WebClient.create(baseUrl);
Проблема: здесь не используется `builder`, что теряет предоставляемые фреймворком фичи.

Предложение: вынести вычисление адреса по умолчанию в переменную и сделать одну общую ветку кода с созданием клиента по адресу через `builder`.

2024-03-05 12:22 UTC, nexen505 commented on scrapper/src/main/java/edu/java/client/StackOverflowClientImpl.java
> +            this.webClient = WebClient.create(baseUrl);
Проблема: здесь не используется `builder`, что теряет предоставляемые фреймворком фичи.

Предложение: вынести вычисление адреса по умолчанию в переменную и сделать одну общую ветку кода с созданием клиента по адресу через `builder`.

2024-03-05 18:29 UTC, svp8 commented on scrapper/src/main/java/edu/java/configuration/SchedulerConfiguration.java
> +public record SchedulerConfiguration(@Bean
Вернул здесь Bean, чтобы Duration забирать. Вы до этого писали, что он излишен, но я не знаю как без создания бина достать время из @ConfigurationProperties и положить в @Scheduled(fixedDelayString = "")

2024-03-06 12:12 UTC, nexen505 commented on scrapper/src/main/java/edu/java/configuration/SchedulerConfiguration.java
> +public record SchedulerConfiguration(@Bean
Через `${app.scheduler.interval}` + ISO-8601 для `Duration`

2024-03-06 16:28 UTC, svp8 commented on scrapper/src/main/java/edu/java/configuration/SchedulerConfiguration.java
Удалил, так как не используем

2024-03-10 08:06 UTC, nexen505 approved these changes

2024-03-10 17:38 UTC, merged