Hw3
svp8/java-course-2024 pull request #3
Opened 2024-03-02 13:57 UTC by svp8

2024-03-12 13:55 UTC, nexen505 requested changes

2024-03-12 13:55 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/commands/CommandList.java
> +    @Autowired
Проблема: field injection - плохая практика, которая тут и не нужна, как я вижу.

Предложение: откатить изменения.

2024-03-12 13:55 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/commands/UntrackCommand.java
> +            linksByChat.remove(chatId);
Вопрос: получается, что удаляются все ссылки из памяти, хотя надо удалить одну. Какая тут логика?

2024-03-12 13:55 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/listener/BotUpdateListener.java
> +    private final HashMap<Long, Command> chatState = new HashMap<>();
Проблема: непотокобезопасная коллекция используется в потокобезопасной среде.

Предложение: сделать логику потокобезопасной.

2024-03-12 13:55 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/commands/UntrackCommand.java
> +        this.linksByChat = new HashMap<>();
Проблема: непотокобезопасная коллекция используется в потокобезопасной среде.

Предложение: сделать логику потокобезопасной.

2024-03-12 13:55 UTC, nexen505 commented on scrapper/src/main/java/edu/java/client/GithubClientImpl.java
> -        this.webClient = builder.baseUrl(ClientUtils.getBaseUrl(baseUrl, BASE_URL)).build();
Проблема: тут изменения выглядят лишними и с ошибками из ДЗ 2.

Предложение: стабилизировать изменения.

2024-03-12 13:55 UTC, nexen505 commented on scrapper/src/main/java/edu/java/client/BotClient.java
> +            this.webClient = WebClient.create(baseUrl);
Проблема: не используется параметр `builder`.

Предложение: не повторять ошибок из ДЗ 2 :)

2024-03-12 13:55 UTC, nexen505 commented on scrapper/src/main/java/edu/java/service/LinkServiceImpl.java
> +        this.inMemoryDb = new HashMap<>();
Проблема: немногопоточная коллекция используется в многопоточной среде.

Предложение: сделать реализацию потокобезопасной.

2024-03-13 17:05 UTC, svp8 commented on bot/src/main/java/edu/java/bot/commands/UntrackCommand.java
> +            linksByChat.remove(chatId);
У меня два режима в untrack: dialog и не dialog. В первый раз выводится весь список ссылок и пользователь должен ввести номер ссылки. После ввода диалог заканчивается и данные о чате удаляются из памяти вместе с ссылками.

2024-03-15 18:37 UTC, nexen505 approved these changes

2024-03-25 16:50 UTC, merged