Hw5 1
svp8/java-course-2024 pull request #7
Opened 2024-03-29 17:59 UTC by svp8

2024-04-01 12:09 UTC, nexen505 requested changes

2024-04-01 12:09 UTC, nexen505 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcAnswerRepository.java
> +    public AnswerEntity update(AnswerEntity entity) {
Мысль: тут и в подобных ситуациях в соседних репозиториях выглядит ненужным и стоит удалить.

2024-04-01 12:09 UTC, nexen505 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcAnswerRepository.java
> +        } catch (EmptyResultDataAccessException e) {
Проблема: тут и в подобных ситуациях в соседних репозиториях выглядит так, что тут это исключение не может быть выброшено.

Предложение: убедиться в этом и убрать.

2024-04-01 12:09 UTC, nexen505 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcAnswerRepository.java
> +        return getById(entity.getId()).get();
Проблема: тут и в подобных ситуациях в соседних репозиториях лишний запрос, хотя можно взять результат `insert`.

Предложение: воспользовать `returning *`.

2024-04-01 12:09 UTC, nexen505 commented on scrapper/src/main/java/edu/java/repository/ChatLinkRepository.java
> +    List<LinkEntity> findLinksByChatId(long id);
Мысль: выглядит так, что этот метод должен быть в `LinkRepository`.

2024-04-01 12:09 UTC, nexen505 commented on scrapper/src/main/java/edu/java/repository/ChatLinkRepository.java
> +    List<ChatEntity> findChatsByLinkId(int id);
Мысль: выглядит так, что этот метод должен быть в `СhatRepository`.

2024-04-01 12:09 UTC, nexen505 commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +        if (chatRepository.getChatById(chatId).isPresent()) {
Проблема: для проверки делается лишний запрос, хотя добавление бросит ошибку при нарушении уникальности.

Предложение: оптимизировать работу с БД.

2024-04-01 12:09 UTC, nexen505 commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcChatService.java
> +        if (chatRepository.getChatById(chatId).isEmpty()) {
Проблема: для проверки делается лишний запрос, хотя можно обработать результат `delete`.

Предложение: оптимизировать работу с БД.

2024-04-01 18:26 UTC, svp8 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcAnswerRepository.java
> +        } catch (EmptyResultDataAccessException e) {
В jdbctemplate оно выпадает, если не найдет запись. В интернете есть способы обрабатывать пустой результат, мне такой вариант показался лучшим.

2024-04-01 18:34 UTC, svp8 commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcAnswerRepository.java
> +        return getById(entity.getId()).get();
Для jdbctemplate не нашел способа возвращать обьект. .update возвращает int. Можно возвращать сгенеренный id, но нам он не нужен. returning не нашел.

2024-04-08 07:15 UTC, nexen505 approved these changes

2024-04-08 18:09 UTC, merged